/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:ff3ee271-8d96-494c-83c4-1e312b429b2d",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_ldBzEUWNq",
    "aws_user_pools_web_client_id": "183oio22k43d2jhulps01de7iq",
    "oauth": {},
    "aws_cognito_login_mechanism": [
        "EMAIL"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": "6",
        "passwordPolicyCharacters": []
    },
    "aws_user_files_s3_bucket": "leadsmanagementsys78f770234a2948328e1ae67b6577b110154-dev",
    "aws_user_files_s3_bucket_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://fciagwmcsbegdjdhjzw4j2lrra.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-bz6g5lsa7vahherz6i3zo4zcju"
};


export default awsmobile;
